Update Readme and archtecture diagram.
IBM/watson-online-store pull request #115
Opened 2017-11-10 19:10 UTC by scottdangelo

Update the Readme for changes to naming of Bluemix.
Update the architecture diagram and add Flow steps.

2017-11-11 02:48 UTC, markstur requested changes
see comments

2017-11-11 02:48 UTC, markstur commented on README.md
> +2. [Create IBM Cloud services](#2-create-bluemix-services)
link says bluemix but dest changed

2017-11-11 02:48 UTC, markstur commented on README.md
> +3. [Get IBM Cloud credentials and add to .env](#3-get-bluemix-services-credentials-and-add-to-env-file)
link says bluemix but dest changed

2017-11-11 02:48 UTC, markstur commented on README.md
> +information is sent to [Deployment Tracker](https://github.com/IBM-IBM Cloud/cf-deployment-tracker-service) and
looks like a search/replace error on this repo link

2017-11-11 02:48 UTC, markstur commented on README.md
> +* **PowerAI**: Get started or get scaling, faster, with a software distribution for machine learning running on the Enterprise Platform for AI: [IBM Power Systems](https://www.ibm.com/ms-en/marketpla
you should remove the ones that aren't related.  No powerai, spark, k8s.  And above I'd remove Data Analytics Code Patterns.

2017-11-11 02:48 UTC, markstur commented on README.md
> +4. The application queries the Cloudant database for the user's information, including the contents of thier shopping cart, and writes the contents back to the database as they change.
s/thier/their/

2017-11-11 02:48 UTC, markstur commented on README.md
> +5. The application interacts with Watson Conversation to determine which response to send to Slack, and information passed back and forth in the conversation context determines actions within the app
s/applicsation/application/

2017-11-13 23:21 UTC, markstur submitted a review, later dismissed
still some issues unless I looked at an old diff

2017-11-13 23:21 UTC, markstur commented on README.md
> +2. Slack send this message to the running application.
s/send/sends/

2017-11-13 23:21 UTC, markstur commented on README.md
> +2. [Create IBM Cloud services](#2-create-IBM-cloud-services)
caps don't work in links

2017-11-13 23:21 UTC, markstur commented on README.md
> +3. [Get IBM Cloud credentials and add to .env](#3-get-IBM-cloud-services-credentials-and-add-to-env-file)
caps don't work in links

2017-11-13 23:21 UTC, markstur commented on README.md
> +* [Watson Discovery](https://www.ibm.com/watson/services/discovery/)* [IBM Cloudant db](https://www.ibm.com/cloud/cloudant)
2 lines got combined here

2017-11-23 00:18 UTC, stevemar approved these changes
this looks good now

2017-11-23 00:18 UTC, merged