Change Bluemix to IBM Cloud
IBM/watson-online-store pull request #123
Opened 2017-12-01 16:04 UTC by dolph

2017-12-01 23:31 UTC, markstur requested changes

2017-12-01 23:31 UTC, markstur commented on README-pt.md
> +- Banco de dados NoSQL IBM Cloud Cloudant
"IBM Cloud Cloudant" doesn't sound right.  Could be just Cloundant or IBM Cloundant. The longer name in docs is "IBM® Cloudant® NoSQL DB for IBM Cloud", but usually it is shortened.

2017-12-01 23:31 UTC, markstur commented on README-pt.md
> +## 2. Criar serviços do IBM Cloud Crie os serviços a seguir:
this would break the link from steps if it wasn't already broken by the translation

2017-12-01 23:31 UTC, markstur commented on README-pt.md
> +## 3. Obter as credenciais de serviços do IBM Cloud e incluir no arquivo .env
this would break the link from steps if it wasn't already broken by the translation

2017-12-01 23:31 UTC, markstur commented on README_ko.md
> +- IBM Cloud Cloudant NoSQL DB
Cloud Cloudant again (doesn't look bad here, just sounds funny)

2017-12-01 23:31 UTC, markstur commented on README_ko.md
> +## 2. IBM Cloud 서비스 생성하기
breaks the link from above

2018-03-16 13:18 UTC, stevemart commented
this was fixed in the main README

2018-03-16 13:18 UTC, closed without merging