Add capability to choose Add or Delete item.
IBM/watson-online-store pull request #23
Opened 2017-03-20 22:49 UTC by scottdangelo

Add the capability to choose which item is added or deleted from
the shopping cart.
Also, improve output of List shopping cart

2017-03-20 22:58 UTC, rhagarty commented on watsononlinestore/watson_online_store.py
> +            formatted_response += "\n" + str(item['cart_number']) + ") " + \
item['cart_number'] is already a str

2017-03-20 23:00 UTC, rhagarty requested changes
small nit

2017-03-20 23:15 UTC, scottdangelo commented on watsononlinestore/watson_online_store.py
> +            formatted_response += "\n" + str(item['cart_number']) + ") " + \
OK. I just changed the name from 'item' to 'cart_number' to make it more clear. Your commit was the one that originally cast item['item'] as a string...

2017-03-21 00:47 UTC, stevemart commented on watsononlinestore/watson_online_store.py
> +            formatted_response += "\n" + str(item['cart_number']) + ") " + \
fixed it up anyway

2017-03-21 00:48 UTC, stevemar approved these changes
+2, LGTM, fixed pep8 error

2017-03-21 00:48 UTC, rhagarty approved these changes
looks good

2017-03-21 00:51 UTC, merged