add korean translation of README
IBM/watson-online-store pull request #92
Opened 2017-07-03 02:15 UTC by stevemart

an IBMer, Sun Ah Jang, provided a translated version of the README

2017-07-03 16:50 UTC, markstur approved these changes

2017-07-03 16:51 UTC, markstur commented on ACKNOWLEDGEMENTS.md
> +* Credit goes to Sunah Jang for providing Korean translations of [README.md](README_ko.md)
Is it Sunah or Sun Ah? I saw both.

2017-07-03 16:51 UTC, markstur requested changes
is the name correct?

2017-07-04 01:00 UTC, stevemart commented on ACKNOWLEDGEMENTS.md
> +* Credit goes to Sunah Jang for providing Korean translations of [README.md](README_ko.md)
Bluepages said Sun Ah, so let's use that.

2017-07-04 01:17 UTC, markstur approved these changes

2017-07-04 01:18 UTC, merged